# Generated by Django 4.2.4 on 2023-09-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_index', models.ImageField(upload_to='gallery')),
                ('h1_text', models.CharField(max_length=40)),
                ('p_text', models.TextField()),
            ],
        ),
    ]
