# Generated by Django 4.2.4 on 2023-10-11 18:52

import adminLayout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLayout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_index_about', models.ImageField(upload_to=adminLayout.models.custom_upload_path_about)),
                ('h1_text', models.CharField(max_length=40)),
                ('p_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='indexlayout',
            name='img_index',
            field=models.ImageField(upload_to=adminLayout.models.custom_upload_path_portada),
        ),
    ]
