# Generated by Django 4.2.4 on 2023-08-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellar', models.CharField(choices=[('Bodega_del_Valle', 'Bodega del Valle'), ('Bodega_Sol_Radiante', 'Bodega Sol Radiante'), ('Bodega_de_los_Andes', 'Bodega de los Andes'), ('Bodega_de_la_Brisa', 'Bodega de la Brisa'), ('Bodega_Aurora', 'Bodega Aurora'), ('Bodega_Vientos_del_Sur', 'Bodega Vientos del Sur'), ('Bodega_Sonora', 'Bodega Sonora'), ('Bodega_Lunaria', 'Bodega Lunaria'), ('Bodega_de_los_Suenos', 'Bodega de los Sueños'), ('Bodega_Euforica', 'Bodega Eufórica')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grape', models.CharField(choices=[('Malbec', 'Malbec'), ('Chardonnay', 'Chardonnay'), ('CabernetSauvignon', 'Cabernet Sauvignon'), ('Bonarda', 'Bonarda')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Mendoza', 'Mendoza'), ('Neuquen', 'Neuquen'), ('La_Rioja', 'La Rioja'), ('San_Juan', 'San Juan'), ('Salta', 'Salta')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(choices=[('Red', 'Tinto'), ('White', 'Blanco'), ('Pink', 'Rosado'), ('Sparkling', 'Espumoso')], default='Red', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='wine_photos')),
                ('cellar', models.ForeignKey(choices=[('Bodega_del_Valle', 'Bodega del Valle'), ('Bodega_Sol_Radiante', 'Bodega Sol Radiante'), ('Bodega_de_los_Andes', 'Bodega de los Andes'), ('Bodega_de_la_Brisa', 'Bodega de la Brisa'), ('Bodega_Aurora', 'Bodega Aurora'), ('Bodega_Vientos_del_Sur', 'Bodega Vientos del Sur'), ('Bodega_Sonora', 'Bodega Sonora'), ('Bodega_Lunaria', 'Bodega Lunaria'), ('Bodega_de_los_Suenos', 'Bodega de los Sueños'), ('Bodega_Euforica', 'Bodega Eufórica')], on_delete=django.db.models.deletion.CASCADE, to='upload_wine.cellar')),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.grape')),
                ('province', models.ForeignKey(choices=[('Mendoza', 'Mendoza'), ('Neuquen', 'Neuquen'), ('La_Rioja', 'La Rioja'), ('San_Juan', 'San Juan'), ('Salta', 'Salta')], on_delete=django.db.models.deletion.CASCADE, to='upload_wine.province')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.variety')),
            ],
        ),
    ]
