# Generated by Django 4.2.4 on 2023-08-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variety', models.CharField(choices=[('Red', 'Tinto'), ('White', 'Blanco'), ('Pink', 'Rosado'), ('Sparkling', 'Espumoso')], max_length=9)),
                ('grape', models.CharField(choices=[('Malbec', 'Malbec'), ('Chardonnay', 'Chardonnay'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Bonarda', 'Bonarda')], max_length=25)),
                ('cellar', models.CharField(choices=[('Bodega del Valle', 'Bodega del Valle'), ('Bodega Sol Radiante', 'Bodega Sol Radiante'), ('Bodega de los Andes', 'Bodega de los Andes'), ('Bodega de la Brisa', 'Bodega de la Brisa'), ('Bodega Aurora', 'Bodega Aurora'), ('Bodega Vientos del Sur', 'Bodega Vientos del Sur'), ('Bodega Sonora', 'Bodega Sonora'), ('Bodega Lunaria', 'Bodega Lunaria'), ('Bodega de los Sueños', 'Bodega de los Sueños'), ('Bodega Eufórica', 'Bodega Eufórica')], max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('province', models.CharField(choices=[('Mendoza', 'Mendoza'), ('Neuquen', 'Neuquen'), ('La Rioja', 'La Rioja'), ('San Juan', 'San Juan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='wine_photos')),
                ('wine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.wine')),
            ],
        ),
    ]
