# Generated by Django 4.2.4 on 2023-08-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_wine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellar', models.CharField(choices=[('Bodega_del_Valle', 'Bodega del Valle'), ('Bodega_Sol_Radiante', 'Bodega Sol Radiante'), ('Bodega_de_los_Andes', 'Bodega de los Andes'), ('Bodega_de_la_Brisa', 'Bodega de la Brisa'), ('Bodega_Aurora', 'Bodega Aurora'), ('Bodega_Vientos_del_Sur', 'Bodega Vientos del Sur'), ('Bodega_Sonora', 'Bodega Sonora'), ('Bodega_Lunaria', 'Bodega Lunaria'), ('Bodega_de_los_Sueños', 'Bodega de los Sueños'), ('Bodega_Eufórica', 'Bodega Eufórica')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grape', models.CharField(choices=[('Malbec', 'Malbec'), ('Chardonnay', 'Chardonnay'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Bonarda', 'Bonarda')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Mendoza', 'Mendoza'), ('Neuquen', 'Neuquen'), ('La_Rioja', 'La Rioja'), ('San_Juan', 'San Juan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(choices=[('Red', 'Tinto'), ('White', 'Blanco'), ('Pink', 'Rosado'), ('Sparkling', 'Espumoso')], max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='wine',
            name='cellar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.cellar'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.grape'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.province'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_wine.variety'),
        ),
    ]
