# Generated by Django 4.2.4 on 2023-08-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_wine', '0002_wineimage_remove_wine_photo_alter_wine_cellar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineimage',
            name='wine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_wine.wine'),
            preserve_default=False,
        ),
    ]
